# Generated by Django 4.0.2 on 2022-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
