# Generated by Django 4.0.2 on 2022-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_address_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('being_customer', 'is a customer.')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
