# Generated by Django 4.0.2 on 2022-02-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_options_alter_product_options_and_more'),
        ('customer', '0002_alter_address_options_address_is_delete_and_more'),
        ('order', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'off_code')},
        ),
    ]
