# Generated by Django 4.0.2 on 2022-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
