# Generated by Django 4.0.2 on 2022-02-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PER', 'Percentage Discount'), ('VAL', 'Value Discount')], max_length=3)),
                ('amount', models.CharField(max_length=20)),
                ('max_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.discount')),
                ('code', models.CharField(max_length=30)),
            ],
            bases=('product.discount',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='product.Category')),
                ('discount', models.ManyToManyField(to='product.Discount')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discount'),
        ),
    ]
