# Generated by Django 4.0.2 on 2022-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_discount_max_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(null=True, related_name='categories', to='product.Category'),
        ),
    ]
