# Generated by Django 4.0.2 on 2022-02-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_discount_code'),
        ('product', '0012_offcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
