# Generated by Django 4.0.2 on 2022-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='max_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
