# Generated by Django 4.0.2 on 2022-02-16 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_discount_amount_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='amount',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
